### ISSUE TITLE
python-csp on PyPI

### ISSUE THREAD

**Issue by fsouza** [futurecore/python-csp#21]
Hi there, I'm the owner of the [python-csp package on PyPI](http://pypi.python.org/pypi/python-csp/). It's the original from Google Code [with a bugfix (to make multiprocessing work on Mac OS)](http://code.google.com/p/python-csp/issues/detail?id=27). Here is it: http://code.google.com/r/franciscossouza-python-csp/

I can add the original owner of the project (@snim2) as owner/maintainer in PyPI.

**Comment by snim2** [comment]
Hi there, I hadn't realised that you had already put this on PyPI, but please do add me as and owner/maintainer.

**Comment by fsouza** [comment]
Sure. What is your nickname on PyPI?

**Comment by snim2** [comment]
It should be snim2 if I've set things up right, give me a shout if I haven't.

**Comment by fsouza** [comment]
Done, I've added you as owner of the package. Please check if everything works fine. You can remove me from the owners list once everything is ok.

**Comment by snim2** [comment]
Brilliant, thanks. I've put you down as a Maintainer rather than owner.
