### ISSUE TITLE
MacOSX compatibility

### ISSUE THREAD

**Issue by snim2** [futurecore/python-csp#7]
From old Google Code repo:

Some of the classes we  use from multiprocessing seem to be unavailable on 
OSX:

``` python
Traceback (most recent call last):
 File 
"/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/
site-packages/python_csp-0.1dev-py2.6.egg/csp/cspprocess.py", line 248, in 
run
   self._target(*self._args, **self._kwargs)
 File "./pi_python2_python-csp_single_separate.py", line 19, in calculator
   channel.write ( sum )
 File 
"/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/
site-packages/python_csp-0.1dev-py2.6.egg/csp/cspprocess.py", line 763, in 
write
   (self.name, self._available.get_value(),
 File 
"/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/
multiprocessing/synchronize.py", line 84, in get_value
   return self._semlock._get_value()
NotImplementedError
```

_Comment 1 by franciscossouza, Jul 29, 2012_ Hi, the problem is with get_value method on Semaphore. It is not implemented in Mac OS. This method is used only for debugging messages, can we just change it? I'm attaching a patch. What do you think about it?

Please notice that I also fixed a call to format method when poisoning a channel.

In this link you can find the patch and a working code: https://gist.github.com/3203281

**Comment by fsouza** [comment]
Are you interested in getting this fixed? I can send the change I've made on Google Code as a pull request here.

**Comment by snim2** [comment]
Fantastic, please do issue the pull request. Thanks!

**Comment by russel** [comment]
On Sat, 2012-10-13 at 10:05 -0700, Sarah Mount wrote:

> Fantastic, please do issue the pull request. Thanks!

I can now test on Snow Leopard and Mountain Lion if that helps.

## 

# Russel.

Dr Russel Winder      t: +44 20 7585 2200   voip: sip:russel.winder@ekiga.net
41 Buckmaster Road    m: +44 7770 465 077   xmpp: russel@winder.org.uk
London SW11 1EN, UK   w: www.russel.org.uk  skype: russel_winder
